# Redis의 공식 이미지를 기본으로 사용
FROM redis:alpine

# Redis 설정 파일을 컨테이너에 복사 (필요한 경우)
# COPY ./redis.conf /usr/local/etc/redis/redis.conf

# Redis 서버 시작
# 기본 설정 파일을 사용하거나 사용자 정의 파일을 사용하려면 명령을 수정하세요.
CMD ["redis-server"]
