services:
    db:
        container_name: dev_mariadb
        image: mariadb:10.11
        env_file:
            - .env
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASS}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASS}
        ports:
            - "3307:3306"
        volumes:
            - mariadb_data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s

    redis:
        container_name: dev_redis
        image: redis:7-alpine
        ports:
            - "6379:6379"
        depends_on:
            db:
                condition: service_healthy

    nginx:
        container_name: dev_web
        image: nginx:stable-alpine
        ports:
            - "80:80"
        depends_on:
            - db
            - redis
        networks:
            - discord-network

networks:
    discord-network:
        driver: bridge

volumes:
    mariadb_data:
