-- V1.2.8_001_add_location_mappings_table.sql
-- 위치 매핑 테이블 생성

USE ${DB_DISCORD};
START TRANSACTION;

CREATE TABLE IF NOT EXISTS location_mappings (
    id BINARY(16) NOT NULL PRIMARY KEY,
    keyword VARCHAR(100) NOT NULL UNIQUE,
    normalized VARCHAR(200) NOT NULL,
    related_keywords JSON,
    typo_variants JSON,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    description VARCHAR(500),
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    KEY idx_location_keyword (keyword),
    KEY idx_location_normalized (normalized)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 초기 데이터 삽입
INSERT INTO location_mappings (id, keyword, normalized, related_keywords, typo_variants, is_active) VALUES
(UNHEX(REPLACE(UUID(), '-', '')), '홍대', '마포구 와우산로', '["합정", "상수", "신촌"]', '["홍대입구", "홍대앞", "홍데"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '강남', '강남구 테헤란로', '["역삼", "삼성", "논현"]', '["깡남", "강남역"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '신촌', '서대문구 연세로', '["이대", "홍대", "아현"]', '["신촌역"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '건대', '광진구 능동로', '["세종대", "어린이대공원", "구의"]', '["건대입구", "건국대"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '잠실', '송파구 올림픽로', '["석촌", "송파", "몽촌토성"]', '["잠실역"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '이대', '서대문구 이화여대길', '["신촌", "아현", "충정로"]', '["이화여대", "이대앞"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '합정', '마포구 독막로', '["상수", "홍대", "망원"]', '["합정역"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '상수', '마포구 와우산로', '["홍대", "합정", "망원"]', '["상수역"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '종로', '종로구 종로', '["광화문", "인사동", "안국"]', '["종로1가", "종로3가"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '명동', '중구 명동길', '["을지로", "충무로", "회현"]', '["명동안", "명동역"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '노량진', '동작구 노량진로', '["흑석", "상도", "대방"]', '["노랭진", "노량진역"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '서울역', '중구 청파로', '["남영", "숙대입구", "회현"]', '["서울역앞"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '성수', '성동구 아차산로', '["뚝섬", "서울숲", "건대"]', '["성수동"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '을지로', '중구 을지로', '["명동", "종로", "충무로"]', '["을지로입구", "을지로3가"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '광화문', '종로구 세종대로', '["종로", "경복궁", "시청"]', '["광화문광장"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '동대문', '중구/동대문구 왕산로', '["청량리", "혜화", "성신여대"]', '["동대문역사문화공원"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '망원', '마포구 월드컵로', '["합정", "상수", "성산"]', '["망원시장", "망원동"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '가로수길', '강남구 압구정로', '["신사", "압구정", "논현"]', '["신사역"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '한남', '용산구 한남대로', '["이태원", "옥수", "순천향"]', '["한남동"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '이태원', '용산구 이태원로', '["녹사평", "한남", "해방촌"]', '["이태원역"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '해방촌', '용산구 신흥로', '["남산", "이태원", "후암동"]', '["해방촌길"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '삼청동', '종로구 삼청로', '["경복궁", "인사동", "북촌"]', '["삼청로"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '북촌', '종로구 북촌로', '["삼청동", "안국", "인사동"]', '["북촌한옥마을"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '인사동', '종로구 인사동길', '["종로", "안국", "삼청동"]', '["인사동길"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '청담', '강남구 도산대로', '["압구정", "신사", "삼성"]', '["청담동"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '압구정', '강남구 언주로', '["청담", "신사", "도산공원"]', '["압구정로데오"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '신사', '강남구 도산대로', '["가로수길", "압구정", "논현"]', '["신사동"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '논현', '강남구 학동로', '["신사", "학동", "강남"]', '["논현역"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '여의도', '영등포구 여의대로', '["국회의사당", "샛강", "마포"]', '["여의도역"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '마포', '마포구 독막로', '["공덕", "애오개", "신촌"]', '["마포역"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '공덕', '마포구 백범로', '["마포", "애오개", "아현"]', '["공덕역"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '아현', '마포구 마포대로', '["이대", "공덕", "충정로"]', '["아현역"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '충정로', '서대문구 통일로', '["아현", "서대문", "시청"]', '["충정로역"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '시청', '중구 세종대로', '["광화문", "을지로", "명동"]', '["서울시청"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '부산', '부산광역시', '[]', '["부산역", "서면", "해운대"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '서면', '부산진구 가야대로', '["범내골", "전포", "부전"]', '["서면역"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '해운대', '해운대구 해운대해변로', '["중동", "송정", "센텀시티"]', '["해운대역"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '대구', '대구광역시', '[]', '["동성로", "반월당", "대구역"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '동성로', '중구 동성로', '["대구역", "반월당", "중앙로"]', '["동성로거리"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '전주', '전라북도 전주시', '[]', '["한옥마을", "객리단길"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '광주', '광주광역시', '[]', '["충장로", "상무지구"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '청주', '충청북도 청주시', '[]', '["성안길", "흥덕구"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '대전', '대전광역시', '[]', '["둔산동", "유성"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '울산', '울산광역시', '[]', '["삼산동", "태화강"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '수원', '경기도 수원시', '[]', '["인계동", "영통"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '성남', '경기도 성남시', '[]', '["분당", "판교"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '일산', '경기도 고양시', '[]', '["백석", "주엽", "마두"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '분당', '경기도 성남시', '[]', '["서현", "정자"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '판교', '경기도 성남시', '[]', '["삼평동", "운중동"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '인천', '인천광역시', '[]', '["부평", "송도", "계양"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '부평', '인천 부평구', '[]', '["부개", "삼산"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '송도', '인천 연수구', '[]', '["국제도시", "캠퍼스타운"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '춘천', '강원도 춘천시', '[]', '["명동", "중앙로"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '강릉', '강원도 강릉시', '[]', '["경포대", "옥계"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '연남동', '마포구 연남로', '["연트럴파크", "홍대"]', '["연남", "연남역"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '혜화', '종로구 혜화로', '["대학로", "성균관대", "동대문"]', '["혜화역", "혜화동"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '대학로', '종로구 대학로', '["혜화", "동대문", "이화동"]', '["대학로역"]', TRUE),
(UNHEX(REPLACE(UUID(), '-', '')), '역삼', '강남구 역삼로', '["강남", "선릉", "삼성"]', '["역삼역", "역삼동"]', TRUE);

COMMIT;