FROM alpine:latest

RUN apk update && apk add nginx && apk add openssl

COPY docker/nginx/conf/nginx.conf /etc/nginx/nginx.conf

COPY docker/nginx/conf/http.d /etc/nginx/http.d
RUN mkdir -p /usr/share/nginx/html
# COPY frontend/dist /usr/share/nginx/html

# RUN chmod +rwx /etc/nginx/tools/nginx.sh

# RUN mkdir /etc/nginx/ssl

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]