FROM alpine:latest

RUN apk update && apk add nginx && apk add openssl
RUN apk add --update nodejs npm

COPY docker/nginx/conf/nginx.conf /etc/nginx/nginx.conf
COPY docker/nginx/tools/nginx.sh /etc/nginx/nginx.sh
RUN chmod +x /etc/nginx/nginx.sh

COPY docker/nginx/conf/http.d /etc/nginx/http.d
RUN mkdir -p /usr/share/nginx/html
RUN mkdir -p /web
COPY frontend/package.json frontend/package-lock.json ./web
COPY frontend ./web
WORKDIR /web
RUN npm install
RUN npm run build
RUN cp -r ./dist /usr/share/nginx/html

# RUN chmod +rwx /etc/nginx/tools/nginx.sh

# RUN mkdir /etc/nginx/ssl

EXPOSE 80

CMD ["/etc/nginx/nginx.sh"]