package com.crimecat.backend.config;

/**
 * 자동 생성된 캐시 이름 상수 클래스
 * CaffeineCacheType enum으로부터 생성됨
 *
 * ⚠️  수정하지 마세요 - 빌드 시 자동 재생성됩니다
 *
 * Generated by: Gradle generateCacheNames task
 * Source: CaffeineCacheType.java
 */
public final class CacheNames {

    public static final String GAME_THEME_ENTITY = "game:theme:entity";
    public static final String USER_THEME_SUMMARY = "user:theme:summary";
    public static final String USER_PERMISSIONS = "user:permissions";
    public static final String USER_PROFILE = "user:profile";
    public static final String POST_NAVIGATION = "post:navigation";
    public static final String BOARD_POST_DETAIL = "board:post:detail";
    public static final String BOARD_POST_COMMENTS = "board:post:comments";
    public static final String VIEW_COUNT = "view:count";
    public static final String WEB_STATS = "web:stats";
    public static final String SCHEDULE_ICAL_DATA = "schedule:ical:data";
    public static final String SCHEDULE_EVENTS = "schedule:events";
    public static final String SCHEDULE_EVENT_LIST = "schedule:event:list";
    public static final String SCHEDULE_EVENT_DETAIL = "schedule:event:detail";
    public static final String SCHEDULE_AVAILABILITY = "schedule:availability";
    public static final String SCHEDULE_PARTICIPANTS = "schedule:participants";
    public static final String SCHEDULE_RECOMMENDED_TIMES = "schedule:recommended:times";
    public static final String SCHEDULE_USER_BLOCKED_DATES = "schedule:user:blocked:dates";
    public static final String USER_CALENDARS = "user:calendars";
    public static final String UNIFIED_CALENDAR_EVENTS = "unified:calendar:events";
    public static final String PERSONAL_CALENDAR_EVENTS = "personal_calendar_events";
    public static final String PERSONAL_BLOCKED_DATES = "personal_blocked_dates";
    public static final String COLOR_PALETTE = "color_palette";
    public static final String PERSONAL_CALENDARS = "personal:calendars";
    public static final String BOT_COMMANDS = "bot:commands";
    public static final String ALL_COMMANDS = "commands:all";
    public static final String COMMAND_CATEGORIES = "commands:categories";
    public static final String GAME_THEME_COMMENTS = "game:theme:comments";
    public static final String ESCAPE_ROOM_COMMENTS = "escape:room:comments";
    public static final String COMMENT_DETAIL = "comment:detail";
    public static final String COMMENT_STATS = "comment:stats";
    public static final String USER_COMMENTS = "user:comments";
    public static final String ALL_NOTICES = "notices:all";
    public static final String NOTICE_CATEGORIES = "notices:categories";
    public static final String TOTAL_SERVERS = "totalServers";
    public static final String TOTAL_USERS = "totalUsers";
    public static final String TOTAL_PLAYERS = "totalPlayers";
    public static final String TOTAL_CREATORS = "totalCreators";
    public static final String CRIME_THEMES = "crimeThemes";
    public static final String ESCAPE_THEMES = "escapeThemes";
    public static final String INTEGRATED_GAME_HISTORY = "integratedGameHistory";
    public static final String USER_GAME_STATISTICS = "userGameStatistics";
    public static final String ESCAPE_ROOM_THEME_STATS = "escapeRoomThemeStats";
    public static final String USER_PROFILE_STATS = "userProfileStats";

    private CacheNames() {
        throw new UnsupportedOperationException("This is a utility class and cannot be instantiated");
    }
}
